export const BACKEND_URL = "http://localhost:3000"
export const SIGNUP_URL = "http://localhost:3000/api/v1/signup"
export const SIGNIN_URL = "http://localhost:3000/api/v1/signin"
export const DASHBOARD_URL = "http://localhost:3000/api/v1/dashboard"
export const CONTENT_URL = "http://localhost:3000/api/v1/content"
export const SHARE_URL = "http://localhost:3000/api/v1/brain/share"